name: Deploy to Production
on:
  push:
    branches:
      - release

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  pre-check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.set_output.outputs.should_run }}
    steps:
      - name: Check if actor is authorized
        id: set_output
        run: |
          if [[ ",${{ secrets.AUTHORIZED_USERS }}," == *",${{ github.actor }},"* ]]; then
            echo "Actor is authorized"
            echo "should_run=true" >> $GITHUB_ENV
          else
            echo "Actor is not authorized"
            echo "should_run=false" >> $GITHUB_ENV
          fi

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0
          cache: "yarn"

      # - name: Run tests
      #   env:
      #     NODE_OPTIONS: "--max-old-space-size=20480"
      #   run: |
      #     yarn env:switch:dev
      #     yarn test:ci

      - name: Setup production credentials
        run: |
          yarn env:switch:prod
          echo "${{ secrets.API_ENV }}" > .env

      - name: Prepare, build and push Docker image
        run: |

          # Prepare: install dependencies, build and lint
          yarn install
          yarn tsc && yarn lint

          # Build the Docker image on Github cloud
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t definya/definya-team:api-latest .
          docker push definya/definya-team:api-latest

      - name: SSH into VPS and update containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }} #! SSH private key
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            # Update Docker image on the VPS
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull definya/definya-team:api-latest

            # Fix to avoid npm not found (applyboy/ssh-action bug)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Update repository code
            cd ~/definya/api  

            # Clean untracked files if any
            git clean -fd 

            git checkout release
            git pull origin release

            bash ~/definya/api/environment/api-refresh-containers.sh
